###############
#
# Linting
#
###############

stages:
  - linting
  - build

ruff:
  stage: linting
  image: registry.dev.info.uvt.ro/sage/sage-lint-environment:2023-04-25
  script:
    - /opt/conda/bin/ruff check .
  only:
    - merge_requests

#################
# Common
#################
.common-python-snippet:
  script:
    - pip install twine build
    - export BASE_VERSION=$(PYTHONPATH=`pwd`/src python3 -c 'import hugin; print(hugin.__version__)')
    - echo BASE_VERSION=${BASE_VERSION}
    - export HUGIN_VERSION="${CI_COMMIT_TAG:-${BASE_VERSION}.dev${CI_PIPELINE_IID}}"
    - sed -i "s|ENV HUGIN_VERSION='0.0.0'|ENV HUGIN_VERSION='${HUGIN_VERSION}'|g"  Dockerfile
    - cat Dockerfile
    - sed -i "s|__version__ = \"${BASE_VERSION}\"|__version__ = '${HUGIN_VERSION}'|g" src/hugin/__init__.py
    - cat src/hugin/__init__.py
    - export HUGIN_VERSION=$(PYTHONPATH=`pwd`/src python3 -c 'import hugin; print(hugin.__version__)')
    - echo "HUGIN_VERSION=${BASE_VERSION}" >> build.env

#################
# Merge Requests
#################
build-pypi-mr:
  image: python:latest
  stage: build
  script:
    - !reference [.common-python-snippet, script]
    - python -m build
    - TWINE_PASSWORD=${CI_JOB_TOKEN} TWINE_USERNAME=gitlab-ci-token python -m twine upload --verbose --repository-url ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi dist/*
  artifacts:
    reports:
      dotenv: build.env
  only:
    - merge_requests

docker-build-amd64-mr:
  image: gcr.io/kaniko-project/executor:debug
  needs:
    - build-pypi-mr
  stage: build
  script:
    - sed -i "s|ENV HUGIN_VERSION='0.0.0'|ENV HUGIN_VERSION='${HUGIN_VERSION}'|g"  Dockerfile
    - |
      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
        tag=""
        echo "Running on default branch '$CI_DEFAULT_BRANCH': tag = 'latest'"
      else
        tag=":$HUGIN_VERSION"
        echo "Running on branch '$CI_COMMIT_BRANCH': tag = $tag"
      fi
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(echo -n ${CI_REGISTRY_USER}:${CI_REGISTRY_PASSWORD} | base64)\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  when: manual
  only:
    - merge_requests


########
# Master
########
build-pypi-master:
  image: python:latest
  stage: build
  script:
    - !reference [.common-python-snippet, script]
    - pip install twine build
    - python -m build
    - python -m twine upload --verbose --repository-url ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi dist/*
  artifacts:
    reports:
      dotenv: build.env
  only:
    - tags
    - master
