configuration:
  model_path: "/data/bid/storage0/sage-storage/homes/eosmith/hugin/models/{name}"
  name: "spacenet2-unet"
  workspace: "/data/bid/storage0/sage-storage/homes/eosmith/hugin/models/{name}"

data_source: !!python/object/apply:hugin.io.FileSystemLoader
  kwds:
    input_source: "/data/bid/storage0/sage-storage/homes/eosmith/hugin/models/spacenet2-unet/vasile/"
    data_pattern: '(?P<COMPETITION_ID>[a-zA-Z0-9]+)_(?P<COMPETITION_NAME>[a-zA-Z0-9]+)_(?P<COMPETITION_STAGE>[a-zA-Z0-9]+)_AOI_(?P<AOI_ID>\d+)_(?P<AOI_NAME>[a-zA-Z0-9]+)_(?P<TYPE>[a-zA-Z0-9-]+)_(?P<IMAGE_ID>[a-zA-Z0-9]+).*\.tif$'
    type_format: '{TYPE}'
    id_format: '{IMAGE_ID}'


trainer: !!python/object/apply:hugin.engine.scene.RasterSceneTrainer
  kwds:
    name: model1_lunetv2_full_seed1993_class3
    window_size: [ 256, 256 ]
    stride_size: 256
    mapping:
      inputs:
        'input_1':
          primary: True
          channels:
            - type: "RGBNIR"
              channel: 1 # 5
              preprocessing: [ ]
            - type: "RGBNIR"
              channel: 2 # 3
              preprocessing: [ ]
            - type: "RGBNIR"
              channel: 3 # 2
              preprocessing: [ ]
            - type: "RGBNIR"
              channel: 4 # 7
              preprocessing: [ ]
      target:
        output_1:
          channels:
            - [ "RGBNIR", 1 ]
    model: !!python/object/apply:hugin.engine.skl.SkLearnModel
      kwds:
        name: standard_scaler_terrasigna
        loop: False
        model_path: "/data/bid/storage0/sage-storage/homes/eosmith/hugin/models/{name}.pickle"
        model: !!python/object/apply:hugin.models.skl.StandardScaler.StandardScaler
          kwds:
            per_channel: True
        batch_size: 1


