configuration:
  model_path: "s3://sagegroup-data/sage/models/{name}"
  name: "lunet5-clasa6-rapita-fold-1"
  workspace: "/home/marian/models/{name}"


data_source: !!python/object/apply:hugin.io.FSSpecFilesystemLoader
  kwds:
    input_source: "s3://sage/public/datasets/paduri/dset-paduri-worldcover2021/"
    data_pattern: '(?P<name>[0-9A-Za-z_]+)_(?P<type>.*)\.tif$'
    fsspec_storage_options:
      endpoint_url: 'https://storage.info.uvt.ro'
      anon: False
    id_format: '{name}'
    type_format: '{type}'
    validation_percent: 0.25
    randomise: True

trainer: !!python/object/apply:hugin.engine.scene.RasterSceneTrainer
         kwds:
          name: unetv14
          stride_size: 256
          window_size: [256, 256]
          format_converter: !!python/object/apply:hugin.io.loader.CategoricalConverter
            kwds:
              num_classes: 2
              channel_last: True
          mapping:
            inputs:
              'input_1':
                primary: True
                channels:
                  - type: "B04"
                    channel: 1
                  - type: "B03"
                    channel: 1
                  - type: "B02"
                    channel: 1
                  - type: "B08"
                    channel: 1
            target:
              output_1:
                #window_shape: [256, 256]
                channels:
                  - [ "GTI", 1 ]
          model: !!python/object/apply:hugin.engine.keras.KerasModel
           kwds:
             name: keras_model
             model_builder: hugin.models.unet.unetv14:unet_v14
             swap_axes: True
             random_seed: 1993
             model_builder_options:
               output_channels: 2
             model_path: "/data/bid/storage0/sage-storage/homes/eosmith/marian/models/{name}"
             batch_size: 16
             epochs: 100
             metrics:
               - categorical_accuracy
               - !!python/name:hugin.tools.utils.dice_coef
               - !!python/object/apply:tensorflow.keras.metrics.MeanIoU
                 kwds:
                   num_classes: 2
               - !!python/object/apply:tensorflow.keras.metrics.IoU
                 kwds:
                   target_class_ids: [0, 1]
                   num_classes: 2
               - !!python/object/apply:tensorflow.keras.metrics.BinaryIoU
                 kwds:
                   target_class_ids: [1]
               - !!python/object/apply:tensorflow.keras.metrics.AUC
                 kwds:
                   num_thresholds: 200
             loss: binary_crossentropy
             checkpoint:
               monitor: val_loss
             enable_multi_gpu: False
             num_gpus: 2
             use_multiprocessing: False
             workers: 1
             max_queue_size: 40
             optimizer: !!python/object/apply:tensorflow.python.keras.optimizer_v2.adam.Adam
               kwds:
                 lr: !!float 0.001 # 0.0001
                 beta_1: !!float 0.9
                 beta_2: !!float 0.999
                 epsilon: !!float 1e-7
             callbacks:
               - !!python/object/apply:tensorflow.keras.callbacks.EarlyStopping
                 kwds:
                   monitor: 'val_loss'
                   min_delta: 0.001
                   patience: 20
                   verbose: 1
                   mode: 'auto'
                   baseline: null
                   restore_best_weights: False
               - !!python/object/apply:tensorflow.keras.callbacks.ReduceLROnPlateau
                 kwds:
                   monitor: 'val_loss'
                   patience: 5
                   factor: !!float 0.2
          
#output: !!python/object/apply:hugin.engine.scene.RasterIOSceneExporter
#  kwds:
#     destination: "/home/stefan/ml/experiments/forestry4_2_predictions"
#     filename_pattern: '{scene_id}.tif'
#     srs_source_component: 'B02'
