definitions:
  b04_scaler: &b04_scaler !!python/object/apply:hugin.preprocessing.standardize.SkLearnStandardizer
    kwds:
      path: "s3://sage/public/datasets/paduri/dset-paduri-worldcover2021/scalers/B04_standardizer.pickle"
      fsspec_storage_options:
        endpoint_url: 'https://storage.info.uvt.ro'
        anon: False
  b03_scaler: &b03_scaler !!python/object/apply:hugin.preprocessing.standardize.SkLearnStandardizer
    kwds:
      path: "s3://sage/public/datasets/paduri/dset-paduri-worldcover2021/scalers/B03_standardizer.pickle"
      fsspec_storage_options:
        endpoint_url: 'https://storage.info.uvt.ro'
        anon: False
  b02_scaler: &b02_scaler !!python/object/apply:hugin.preprocessing.standardize.SkLearnStandardizer
    kwds:
      path: "s3://sage/public/datasets/paduri/dset-paduri-worldcover2021/scalers/B02_standardizer.pickle"
      fsspec_storage_options:
        endpoint_url: 'https://storage.info.uvt.ro'
        anon: False
  b08_scaler: &b08_scaler !!python/object/apply:hugin.preprocessing.standardize.SkLearnStandardizer
    kwds:
      path: "s3://sage/public/datasets/paduri/dset-paduri-worldcover2021/scalers/B08_standardizer.pickle"
      fsspec_storage_options:
        endpoint_url: 'https://storage.info.uvt.ro'
        anon: False
configuration:
#  model_path: "s3://sagegroup-data/sage/models/{name}"
  name: "unet-forestry-dev"
  workspace: "/home/marian/models/{name}"


data_source: !!python/object/apply:hugin.io.FSSpecFilesystemLoader
  kwds:
    input_source: "s3://sage/public/datasets/paduri/paduri-worldcover2021/data/training/train"
    validation_source: "s3://sage/public/datasets/paduri/paduri-worldcover2021/data/training/validation"
    data_pattern: '(?P<name>[0-9A-Za-z_]+)_(?P<type>.*)\.tif$'
    fsspec_storage_options:
      endpoint_url: 'https://storage.info.uvt.ro'
      anon: False
    id_format: '{name}'
    type_format: '{type}'
    validation_percent: 0.25
    randomise: True
    persist_file: ""

trainer: !!python/object/apply:hugin.engine.scene.RasterSceneTrainer
         kwds:
          name: unetv14
          stride_size: 190
          window_size: [256, 256]
          format_converter: !!python/object/apply:hugin.io.loader.CategoricalConverter
            kwds:
              num_classes: 2
              channel_last: True
          mapping:
            inputs:
              'input_1':
                primary: True
                channels:
                  - type: "B04"
                    channel: 1
                    preprocessing:
                      - *b04_scaler
                  - type: "B03"
                    channel: 1
                    preprocessing:
                      - *b03_scaler
                  - type: "B02"
                    channel: 1
                    preprocessing:
                      - *b02_scaler
                  - type: "B08"
                    channel: 1
                    preprocessing:
                      - *b08_scaler
            target:
              output_1:
                #window_shape: [256, 256]
                channels:
                  - [ "GTI", 1 ]
          model: !!python/object/apply:hugin.engine.keras.KerasModel
           kwds:
             name: keras_model
             model_builder: !!python/object/apply:hugin.models.unet.UNet
               kwds:
                 name: "sample"
                 batch_normalization: False
             swap_axes: True
             random_seed: 1993
             model_builder_options:
               output_channels: 2
             model_path: "/data/bid/storage0/sage-storage/homes/eosmith/marian/models/{name}"
             batch_size: 14
             epochs: 100
             metrics:
               - categorical_accuracy
               - !!python/name:hugin.tools.utils.dice_coef
               - !!python/object/apply:tensorflow.keras.metrics.BinaryIoU
                 kwds:
                   target_class_ids: [1]
               - !!python/object/apply:tensorflow.keras.metrics.AUC
                 kwds:
                   num_thresholds: 200
             loss: binary_crossentropy
             checkpoint:
               monitor: val_loss
             enable_multi_gpu: False
             num_gpus: 2
             use_multiprocessing: False
             workers: 1
             max_queue_size: 40
             optimizer: !!python/object/apply:tensorflow.keras.optimizers.Adam
               kwds:
                 lr: !!float 0.001 # 0.0001
                 beta_1: !!float 0.9
                 beta_2: !!float 0.999
                 epsilon: !!float 1e-7
             callbacks:
               - !!python/object/apply:tensorflow.keras.callbacks.EarlyStopping
                 kwds:
                   monitor: 'val_loss'
                   min_delta: 0.001
                   patience: 20
                   verbose: 1
                   mode: 'auto'
                   baseline: null
                   restore_best_weights: False
               - !!python/object/apply:tensorflow.keras.callbacks.ReduceLROnPlateau
                 kwds:
                   monitor: 'val_loss'
                   patience: 5
                   factor: !!float 0.2
          
#output: !!python/object/apply:hugin.engine.scene.RasterIOSceneExporter
#  kwds:
#     destination: "/home/stefan/ml/experiments/forestry4_2_predictions"
#     filename_pattern: '{scene_id}.tif'
#     srs_source_component: 'B02'
